### ISSUE TITLE
Miscellaneous code changes

### ISSUE THREAD

**Issue by bbusenius** [uchicago-library/research_data#7]
- [x] Add a show child pages option to standard pages.
- [x] Add the ability to associate a research lifecycle phase with a standard page and have the related services display on it.
- [x] Make news stories appear on the home page.
- [x] Display category tags, clean link, and button on service pages.
- [x] Fix breadcrumbs for pages that use `RoutablePageMixin`.
- [x] Add `wagtailuserbar`.

**Comment by vitorgomateus** [comment]
>  Add a show child page option to standard pages.

If the child page does not have "Show in menus" will it be displayed in the parent page?

**Comment by bbusenius** [comment]
Good question. It can be however we want. What's best in this case?

**Comment by vitorgomateus** [comment]
I'd go with not showing them.
